### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#10]
**Value Proposition**
As a player i need a board to play the game

**Discription**
<img width="277" alt="Bildschirmfoto 2022-09-28 um 09 13 33" src="https://user-images.githubusercontent.com/76123735/192713018-eca4871c-ac01-42ed-94f8-5374cbaec696.png">

**Acception Criteria**
- [ ] the Game would have a 4x4 grid with 16 cards
- [ ] each Card will have a front and a back

**Tasks**
- [ ] create a new branch
- [ ] create a new folder with memory
- [ ] add a `<h1>` with the string "Memory"
- [ ] create a array with the length of 16
- [ ] use the map function to iterate over it and display cards
- [ ] we use absolute position backface visibility
- [ ] other styles for flipped and found
