### ISSUE TITLE
Navigation Home

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#11]
**Value Proposition**
As User i need a Navigation Site to choose a game

**Discription**

**Acception Criteria**
- [ ] show the games
- [ ] route to the games

**Tasks**
- [ ] create a `<h1>` with "Gambler"
- [ ] let show example pictures with link to the game
- [ ]

**Comment by MerleMak** [comment]
Hi andy, please rephrase your acceptance(!) criteria so it sounds less technical :)

**Comment by MerleMak** [comment]
What i meant was more like

**Acceptance** Criteria
- [ ] the minigames are displayed on a overview page 
- [ ] when clicking on one game icon the game is initialized

**Comment by AndySch666** [comment]
Thanks ^^
