### ISSUE TITLE
shuffle cards and couples

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#12]
**Value Proposition**
As a player i need the cards shuffeld and find pairs to play

**Discription**
<img width="277" alt="Bildschirmfoto 2022-09-28 um 11 00 50" src="https://user-images.githubusercontent.com/76123735/192737133-c8d819b8-6fae-408d-8e56-9c2a0709b667.png">

**Acception Criteria**
- [ ] cards should be shuffeld by game start
- [ ] matching pairs should be found

**Tasks**
- [ ] write a random function for shuffle
- [ ] create a initialize function, which will be used on the component mount
- [ ] write a card function for active cardstatus by click
- [ ] write a use function for card matches

**Comment by AndySch666** [comment]
Thanks, i give more information also for the other stories ;)
