### ISSUE TITLE
Game over and restart

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#13]
**Value Proposition**
A game needs a ending and a restart button for another game

**Description**
<img width="277" alt="Bildschirmfoto 2022-09-28 um 11 12 27" src="https://user-images.githubusercontent.com/76123735/192739784-a69c2155-d566-43a2-bf0b-bc1bfaf61c39.png">

**Acception Criteria**
- [ ] Game over
- [ ] restart
- [ ] moves

**Tasks**
- [ ] write game over operation
- [ ] write restart button
- [ ] write reatart function
- [ ] let show how many moves are needed
