### ISSUE TITLE
Snake Matchfield

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#17]
**Value Proposition**

As a player you need a Matchfield and the Charakter (Snake)

**Description**

<img width="322" alt="Snake 1" src="https://user-images.githubusercontent.com/76123735/194361350-36ccf48f-a7cf-4bf0-bdbc-1374df707895.png">

**Acception Criteria**

- [ ] let show the Machtchfield
- [ ] let show the Snake as Charakter

**Tasks**

- [ ] create a new branch
- [ ] create a new file with the name Snake.js
- [ ] create a `<h1>` with the title Snake
- [ ] write the Code for the Matchfield
- [ ] write the Code for the Snake
