### ISSUE TITLE
Movement and change direction

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#18]
**Value Proposition**

As a player need movement and  a input for changing direction

**Discription**

<img width="322" alt="Snake 2" src="https://user-images.githubusercontent.com/76123735/194364270-ee498617-3457-4ad3-870f-8b1a251c592e.png">

**Acception Criteria**

- [ ] the Snake should move horizontal and vertical
- [ ] the Snake should move automaticly
- [ ] using Arrow Keys to control the Snake 

**Tasks**

- [ ] create a new branch `feature/Movement`
- [ ] write logic for horizontal movement
- [ ] write logic for vertial movement
- [ ] write logic for automatical movement
- [ ] write logic for change direction
