### ISSUE TITLE
Boundry, Food and Score

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#19]
**Value Proposition**

for play the game you need a boundry, food and score

**Discription**

<img width="322" alt="Snake 3" src="https://user-images.githubusercontent.com/76123735/194367242-3539a10b-749d-463c-84aa-16740ebaea52.png">

**Acception Criteria**

- [ ] add a boundry, when Snake colide the boundry game ends
- [ ] add food for collecting and earn points
- [ ] add a score counter

**Tasks**

- [ ] create a new branch `feature/boundry`
- [ ] write logic for colide with wall and body of the Snake
- [ ] write logic for random food spawn
- [ ] write logic for growing body, when Snake collect food
- [ ] write logic for the score counter
- [ ] add a button to get back to game library
