### ISSUE TITLE
X O Matchfield

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#2]
**Value Proposition**
As a Player I need a matchfield to be able to play the game

**Description**

<img width="279" alt="Skizze XO Game " src="https://user-images.githubusercontent.com/76123735/190203592-1aa8510a-8e5b-48f9-80bd-d6a4d8ae1c92.png">

**Acceptance Criteria**
describe every scenario in detail

- [ ] when clicked in matchfield let show a X
- [ ] when NPCs turn let show an O
- [ ] when Home Button is clicked restart the game

**Tasks**
list the tasks that need to be performed within the dev team
e.g. Components, Storybook, testing

- [ ] create a branch
- [ ] create a <h1> with "X O - Game"
- [ ] create a matchfield
- [ ] write logic for the matchfield
- [ ] write logic for the NPC
- [ ] write logic for the Home Button

**Comment by macfrei** [comment]
Hi Andi, I will add some suggestions here. 

The text _"describe every scenario in detail"_ under `Acceptance Criteria` could be deleted as it initially was just to show you what to write.

Same goes for _"list the tasks that need to be performed within the dev team, e.g. Components, Storybook, testing"_ under `Tasks`. You don't need that.

Please be careful with the formatting of your user stories. Under `Tasks` the `with "X O - Game"` is a bit off and there isn't a clear task defined on what to do with it. 

From a programming point of view, it might be quite a complicated first user story. The functionality which will be most complicated is to program the NPC logic. I might suggest to first program the game for two players on the same device. That way you wouldn't need the NPC logic right away but could add that as a feature later on.

Since the `Home button` restarts the game, why not rename it to `Restart game`? At first you will only have one screen anyways. That might be a bit easier to understand for your users. 

Other than that it looks good 👍 
Let me know if you have any questions or comments.

**Comment by macfrei** [comment]
Looks much much better, thank you! 💯
