### ISSUE TITLE
 food and score

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#21]
**Value Proposition**

As a player i need a score counter to be able to get a challenge

**Discription**

<img width="322" alt="Snake 4" src="https://user-images.githubusercontent.com/76123735/194530261-ed1f24cf-48f6-4908-8753-ca498f9a05a6.png">

**Acception Criteria**

- [ ] add food for collecting and earn points
- [ ] add a score counter

**Tasks**

- [ ] create a new branch `feature/score`
- [ ] write logic for random food spawn
- [ ] write logic for growing body, when Snake collect food
- [ ] write logic for the score counter
- [ ] write lose operation
- [ ] add a button to get back to game library
