### ISSUE TITLE
add player name input

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#3]
**Value Proposition**
As a player i need a name to be able to have a name

**Description**

<img width="279" alt="Skizze XO Game 2" src="https://user-images.githubusercontent.com/76123735/190205555-00fee2a5-5790-44e0-bd55-6260be1a0afa.png">

**Aceptance Criteria**

- [ ] the input field has a max length of 20 characters
- [ ] when clicked the OK Button confirm as player name

**Tasks**

- [ ] create a form with input field 
- [ ] before input is put into the state, it is trimmed to avoid whitespace
- [ ] set a ma length for input
- [ ] change the form to player name
- [ ] crate a button

**Comment by OmerAdam34** [comment]
Hi Andy, very interesting project. 
Maybe change  your benefit of your user story to "individual character":

"As a player 
i need a name 
to play as an individual character."
