### ISSUE TITLE
Score counter

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#4]
**Value Proposition**
As a player i need a score to be able to see the wins

**Discription**

<img width="279" alt="Skizze XO Game 3" src="https://user-images.githubusercontent.com/76123735/190208249-b2653199-d94a-4967-af5c-44d29844822a.png">
<img width="279" alt="Skizze XO Game 4" src="https://user-images.githubusercontent.com/76123735/190209738-c89ad1cf-2d36-439f-a2be-82dc45807908.png">

**Accept Criteria**

- [ ] when player wins count 1 to score
- [ ] show a win / lose animation

**Tasks**

- [ ] create a animation win and lose
- [ ] write logic for win / lose operation
- [ ] create a score counter
- [ ] write logic for counter
