### ISSUE TITLE
CPU Player

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#5]
**Value Proposition**
As player i need a opponent to be able to play a match

**Description**
<img width="270" alt="X O Game 5" src="https://user-images.githubusercontent.com/76123735/190616311-d6664053-b03e-4aa9-8e43-3824507b4c53.png">

**Accept Criteria**
- [ ] a CPU player
- [ ] in second turn let show a O
 
**Tasks**
– [ ] create a new branch
- [ ] write a function to set the turn
- [ ] write logic for CPU player
- [ ] write a sleep function for CPU player thinking
- [ ] write logic for let show the O

**Comment by macfrei** [comment]
Hi, I think a better wording for the Acceptance Criteria for the second task would be:
```
every second turn the CPU adds a O on the screen
```
Other than that, it looks good and I am glad that you are separating your stories into shorter parts. 👍
