### ISSUE TITLE
winning operation

### ISSUE THREAD

**Issue by AndySch666** [AndySch666/capstone-project#7]
**Value Proposition**
As a player i need a winning operation to end the game

**Description**

<img width="249" alt="Game 7" src="https://user-images.githubusercontent.com/76123735/191721343-783c2b10-4581-4933-830d-6072fd00a16c.png">

**Acception Criteria**
- [ ] the game should have an end
- [ ] show a win or lose 

**Tasks**
- [ ] create a new branch
- [ ] write a win/lose operation
- [ ] show win or lose

**Comment by DanielGennat** [comment]
lgtm :)
